const CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA = 'data';
const CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_DATE = 'date';
const CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_INSTANCES = 'instances';
const CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_MEMORY = 'memory';
const CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_VCPU = 'vcpu';

const rhelApiTypes = {
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_DATE,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_INSTANCES,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_MEMORY,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_VCPU
};

export {
  rhelApiTypes as default,
  rhelApiTypes,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_DATE,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_INSTANCES,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_MEMORY,
  CLOUDIGRADE_API_RESPONSE_CONCURRENT_DATA_VCPU
};
