const RHSM_API_RESPONSE_CAPACITY_DATA = 'data';
const RHSM_API_RESPONSE_CAPACITY_DATA_TYPES = {
  DATE: 'date',
  SOCKETS: 'sockets',
  PHYSICAL_SOCKETS: 'physical_sockets',
  HYPERVISOR_SOCKETS: 'hypervisor_sockets',
  HAS_INFINITE: 'has_infinite_quantity'
};
const RHSM_API_RESPONSE_CAPACITY_META = 'meta';
const RHSM_API_RESPONSE_CAPACITY_META_TYPES = {
  COUNT: 'count'
};

const RHSM_API_RESPONSE_PRODUCTS_DATA = 'data';
const RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES = {
  DATE: 'date',
  SOCKETS: 'sockets',
  PHYSICAL_SOCKETS: 'physical_sockets',
  HYPERVISOR_SOCKETS: 'hypervisor_sockets',
  HAS_DATA: 'has_data'
};
const RHSM_API_RESPONSE_PRODUCTS_META = 'meta';
const RHSM_API_RESPONSE_PRODUCTS_META_TYPES = {
  COUNT: 'count'
};

const RHSM_API_QUERY_GRANULARITY = 'granularity';
const RHSM_API_QUERY_GRANULARITY_TYPES = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  QUARTERLY: 'quarterly'
};
const RHSM_API_QUERY_LIMIT = 'limit';
const RHSM_API_QUERY_OFFSET = 'offset';
const RHSM_API_QUERY_START_DATE = 'beginning';
const RHSM_API_QUERY_END_DATE = 'ending';

const rhelApiTypes = {
  RHSM_API_RESPONSE_CAPACITY_DATA,
  RHSM_API_RESPONSE_CAPACITY_DATA_TYPES,
  RHSM_API_RESPONSE_CAPACITY_META,
  RHSM_API_RESPONSE_CAPACITY_META_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_TYPES,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};

export {
  rhelApiTypes as default,
  rhelApiTypes,
  RHSM_API_RESPONSE_CAPACITY_DATA,
  RHSM_API_RESPONSE_CAPACITY_DATA_TYPES,
  RHSM_API_RESPONSE_CAPACITY_META,
  RHSM_API_RESPONSE_CAPACITY_META_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_TYPES,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};
