const RHSM_API_RESPONSE_PRODUCTS_DATA = 'data';
const RHSM_API_RESPONSE_PRODUCTS_DATA_CORES = 'cores';
const RHSM_API_RESPONSE_PRODUCTS_DATA_DATE = 'date';
const RHSM_API_RESPONSE_PRODUCTS_DATA_INSTANCES = 'instance_count';
const RHSM_API_RESPONSE_PRODUCTS_DATA_SOCKETS = 'sockets';
const RHSM_API_RESPONSE_PRODUCTS_META = 'meta';
const RHSM_API_RESPONSE_PRODUCTS_META_COUNT = 'count';

const RHSM_API_QUERY_GRANULARITY = 'granularity';
const RHSM_API_QUERY_GRANULARITY_TYPES = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  QUARTERLY: 'quarterly'
};
const RHSM_API_QUERY_LIMIT = 'limit';
const RHSM_API_QUERY_OFFSET = 'offset';
const RHSM_API_QUERY_START_DATE = 'beginning';
const RHSM_API_QUERY_END_DATE = 'ending';

const rhelApiTypes = {
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_CORES,
  RHSM_API_RESPONSE_PRODUCTS_DATA_DATE,
  RHSM_API_RESPONSE_PRODUCTS_DATA_INSTANCES,
  RHSM_API_RESPONSE_PRODUCTS_DATA_SOCKETS,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_COUNT,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};

export {
  rhelApiTypes as default,
  rhelApiTypes,
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_CORES,
  RHSM_API_RESPONSE_PRODUCTS_DATA_DATE,
  RHSM_API_RESPONSE_PRODUCTS_DATA_INSTANCES,
  RHSM_API_RESPONSE_PRODUCTS_DATA_SOCKETS,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_COUNT,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};
