const RHSM_API_RESPONSE_CAPACITY_DATA = 'data';
const RHSM_API_RESPONSE_CAPACITY_DATA_TYPES = {
  DATE: 'date',
  SOCKETS: 'sockets',
  PHYSICAL_SOCKETS: 'physical_sockets',
  HYPERVISOR_SOCKETS: 'hypervisor_sockets',
  HAS_INFINITE: 'has_infinite_quantity'
};
const RHSM_API_RESPONSE_CAPACITY_META = 'meta';
const RHSM_API_RESPONSE_CAPACITY_META_TYPES = {
  COUNT: 'count'
};

const RHSM_API_RESPONSE_PRODUCTS_DATA = 'data';
const RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES = {
  DATE: 'date',
  SOCKETS: 'sockets',
  PHYSICAL_SOCKETS: 'physical_sockets',
  HYPERVISOR_SOCKETS: 'hypervisor_sockets',
  HAS_DATA: 'has_data'
};
const RHSM_API_RESPONSE_PRODUCTS_META = 'meta';
const RHSM_API_RESPONSE_PRODUCTS_META_TYPES = {
  COUNT: 'count'
};

const RHSM_API_PATH_RHEL_ID_TYPES = {
  RHEL: 'RHEL',
  COMPUTE_NODE: 'RHEL Compute Node',
  DESKTOP: 'RHEL Desktop',
  SERVER: 'RHEL Server',
  WORKSTATION: 'RHEL Workstation',
  ARM: 'RHEL for ARM',
  IBM_POWER: 'RHEL for IBM Power',
  IBM_Z: 'RHEL for IBM z',
  X86: 'RHEL for x86'
};

const RHSM_API_QUERY_GRANULARITY = 'granularity';
const RHSM_API_QUERY_GRANULARITY_TYPES = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  QUARTERLY: 'quarterly'
};
const RHSM_API_QUERY_LIMIT = 'limit';
const RHSM_API_QUERY_OFFSET = 'offset';
const RHSM_API_QUERY_START_DATE = 'beginning';
const RHSM_API_QUERY_END_DATE = 'ending';

const rhsmApiTypes = {
  RHSM_API_RESPONSE_CAPACITY_DATA,
  RHSM_API_RESPONSE_CAPACITY_DATA_TYPES,
  RHSM_API_RESPONSE_CAPACITY_META,
  RHSM_API_RESPONSE_CAPACITY_META_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_TYPES,
  RHSM_API_PATH_RHEL_ID_TYPES,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};

export {
  rhsmApiTypes as default,
  rhsmApiTypes,
  RHSM_API_RESPONSE_CAPACITY_DATA,
  RHSM_API_RESPONSE_CAPACITY_DATA_TYPES,
  RHSM_API_RESPONSE_CAPACITY_META,
  RHSM_API_RESPONSE_CAPACITY_META_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_DATA,
  RHSM_API_RESPONSE_PRODUCTS_DATA_TYPES,
  RHSM_API_RESPONSE_PRODUCTS_META,
  RHSM_API_RESPONSE_PRODUCTS_META_TYPES,
  RHSM_API_PATH_RHEL_ID_TYPES,
  RHSM_API_QUERY_GRANULARITY,
  RHSM_API_QUERY_GRANULARITY_TYPES,
  RHSM_API_QUERY_LIMIT,
  RHSM_API_QUERY_OFFSET,
  RHSM_API_QUERY_START_DATE,
  RHSM_API_QUERY_END_DATE
};
