const GET_GRAPH_CAPACITY_RHEL = 'GET_GRAPH_CAPACITY_RHEL';
const GET_GRAPH_REPORT_RHEL = 'GET_GRAPH_REPORT_RHEL';
const SET_GRAPH_RHEL_GRANULARITY = 'SET_GRAPH_RHEL_GRANULARITY';

export { GET_GRAPH_CAPACITY_RHEL, GET_GRAPH_REPORT_RHEL, SET_GRAPH_RHEL_GRANULARITY };
