const GET_GRAPH_CAPACITY_RHSM = 'GET_GRAPH_CAPACITY_RHSM';
const GET_GRAPH_REPORT_RHSM = 'GET_GRAPH_REPORT_RHSM';
const SET_GRAPH_GRANULARITY_RHSM = 'SET_GRAPH_GRANULARITY_RHSM';

export { GET_GRAPH_CAPACITY_RHSM, GET_GRAPH_REPORT_RHSM, SET_GRAPH_GRANULARITY_RHSM };
