const GET_GRAPH_CAPACITY_RHSM = 'GET_GRAPH_CAPACITY_RHSM';
const GET_GRAPH_REPORT_RHSM = 'GET_GRAPH_REPORT_RHSM';
const GET_GRAPH_REPORT_CAPACITY_RHSM = 'GET_GRAPH_REPORT_CAPACITY_RHSM';
const GET_HOSTS_INVENTORY_RHSM = 'GET_HOSTS_INVENTORY_RHSM';
const GET_HOSTS_INVENTORY_GUESTS_RHSM = 'GET_HOSTS_INVENTORY_GUESTS_RHSM';

/**
 * RHSM API action, reducer types.
 *
 * @type {{GET_GRAPH_REPORT_CAPACITY_RHSM: string, GET_HOSTS_INVENTORY_GUESTS_RHSM: string,
 *     GET_GRAPH_CAPACITY_RHSM: string, GET_HOSTS_INVENTORY_RHSM: string, GET_GRAPH_REPORT_RHSM: string}}
 */
const rhsmTypes = {
  GET_GRAPH_CAPACITY_RHSM,
  GET_GRAPH_REPORT_RHSM,
  GET_GRAPH_REPORT_CAPACITY_RHSM,
  GET_HOSTS_INVENTORY_RHSM,
  GET_HOSTS_INVENTORY_GUESTS_RHSM
};

export {
  rhsmTypes as default,
  rhsmTypes,
  GET_GRAPH_CAPACITY_RHSM,
  GET_GRAPH_REPORT_RHSM,
  GET_GRAPH_REPORT_CAPACITY_RHSM,
  GET_HOSTS_INVENTORY_RHSM,
  GET_HOSTS_INVENTORY_GUESTS_RHSM
};
