name: Pull request
on:
  pull_request:
    branches: [ master, main, prod, stage, test**, qa**, dev**, ci** ]
env:
  BRANCH: ${{ github.base_ref }}

jobs:
  Integration-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node.js packages cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn
            ${{ runner.os }}-${{ matrix.node-version }}-
            ${{ runner.os }}-
      - name: Install Node.js packages
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint and test
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn test', { stdio: 'pipe' })}`);
            } catch ({ stdout, stderr }) {
              core.setFailed(`${stdout}\n${stderr}`);
            }
      - name: Code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
      - name: Confirm beta integration
        if: ${{ success() }}
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn build', { stdio: 'pipe' })}`);
            } catch ({ stdout, stderr }) {
              core.setFailed(`${stdout}\n${stderr}`);
            }
        env:
          BUILD_STAGE: Beta
      - name: Confirm stable integration
        if: ${{ success() }}
        uses: actions/github-script@v2
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              console.log(`${execSync('yarn build', { stdio: 'pipe' })}`);
            } catch ({ stdout, stderr }) {
              core.setFailed(`${stdout}\n${stderr}`);
            }
        env:
          BUILD_STAGE: Stable
